# 应用名称
spring:
  application:
    name: objectstorage
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
server:
  port: 8088
# MinIO对象存储相关配置
minio:
#  endpoint: http://106.15.57.126:9090 #MinIO服务所在地址
  endpoint:  http://192.168.0.100:9000 #MinIO服务所在地址
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8089/eureka/
